services:
  server:
    build: .
    command: npm run dev
    ports:
      - 3000:8080
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
